##################################################
# Name: wrangler.toml
# Description: Cloudflare Workers config
##################################################

#########################
# Global
#########################

# The name of the Worker script.
name = "website-saltlabs"

# The account id that matches the worker
account_id = "6d6a8fb1f9f3f38b7374d4974c0743cf"

# Deploy to the workers.dev subdomain?
workers_dev = false

# Compatibility date for the Workers runtime.
compatibility_date = "2023-02-25"

# The entry point for your Worker.
main = "workers-site/index.js"

# Usage model for the Worker (bundled or unbound)
usage_model = "bundled"

# Send logs to the console.
logpush = true

#########################
[site]
#########################

bucket = "./public"

#include = ["upload_dir"]
#exclude = ["ignore_dir"]

#########################
[env.staging]
#########################

# Deploy to the workers.dev subdomain?
workers_dev = false

# The route where to use the worker (Personal domains)
# Ref: https://developers.cloudflare.com/workers/about/routes/
routes = [
	{ pattern = "staging.saltlabs.tech", custom_domain = true },
]

kv_namespaces = [
  { binding = "website-saltlabs-staging>", id = "1cfa21d623f94c548401234063b77030" }
]

#########################
[env.production]
#########################

# Deploy to the workers.dev subdomain?
workers_dev = false

# The route where to use the worker (Personal domains)
# Ref: https://developers.cloudflare.com/workers/about/routes/
routes = [
	{ pattern = "www.saltlabs.tech", custom_domain = true },
	{ pattern = "saltlabs.tech", custom_domain = true },
]

kv_namespaces = [
  { binding = "website-saltlabs-production>", id = "911168d413a648cba7ca4cb989f93019" }
]
