##################################################
# Name: wrangler.toml
# Description: Cloudflare Workers config
##################################################

#########################
# Global
#########################

# The name of the Worker script.
name = "website-saltlabs"

# How wrangler will build the Project.
# webpack, javascript, rust
type = "webpack"

# The account id that matches the worker
account_id = "6d6a8fb1f9f3f38b7374d4974c0743cf"

# Deploy to the workers.dev subdomain?
workers_dev = false

#########################
[site]
#########################

bucket = "public"
entry-point = "workers-site"

#########################
[env.staging]
#########################

# Deploy to the workers.dev subdomain?
workers_dev = false

# The zone ID to run the script on (Personal domains)
zone_id = "0a1e8df1e89d38193ee0f1efeb7613e1"

# The route where to use the worker (Personal domains)
# Ref: https://developers.cloudflare.com/workers/about/routes/
routes = [ "staging.saltlabs.tech/*" ]

#########################
[env.production]
#########################

# Deploy to the workers.dev subdomain?
workers_dev = false

# The zone ID to run the script on (Personal domains)
zone_id = "0a1e8df1e89d38193ee0f1efeb7613e1"

# The route where to use the worker (Personal domains)
# Ref: https://developers.cloudflare.com/workers/about/routes/
routes = [ "saltlabs.tech/*", "www.saltlabs.tech/*" ]
